language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - ruby-head
  - 2.0
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.0
    - rvm: rbx-18mode
    - rvm: rbx-19mode
  fast_finish: true
